[package]
name = "librcekunit_cli"
version = "0.1.0"
authors.workspace = true
categories.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
documentation.workspace = true
publish = false

[[bin]]
name = "cekunit"
path = "src/main.rs"

[dependencies]
librcekunit_client = { path = "../../librcekunit_client" }
librcekunit_handler = { path = "../../librcekunit_handler" }
librcekunit_examples = { path = "../../librcekunit_examples" }
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time"] }

[lints]
workspace = true
