[package]
name = "librcekunit"
version = "2.0.2"
edition = "2024"
authors = ["mroczect <neuxdev1@gmail.com>"]
description = "a pure library implementation into rust programming language for admin panel cekunit"

license = "AGPL-3.0"
readme = "README.md"

repository = "https://codeberg.org/mroczect/librcekunit"
homepage = "https://codeberg.org/mroczect/librcekunit"

keywords = [
    "cekunit",
    "admin-panel",
    "library",
    "rust",
    "rcekunit"]

categories = [
    "api-bindings",
    "network-programming",
    "web-programming"
]

exclude = [
    ".github/*",
    "tests/*",
    "target/*",
    ".local/*",
    ".vscode/*"
]

[lib]
name = "librcekunit"
path = "src/lib.rs"

[dependencies]
dotenvy = "0.15.7"
log = "0.4.30"
reqwest = { version = "0.13.3", features = ["cookies", "json", "multipart", "form", "query"] }
scraper = "0.27.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
thiserror = "2.0.18"
tokio = { version = "1.52.3", features = ["full"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }

[dev-dependencies]
mockito = "1.7.2"
httpmock = "0.8.3"
tokio = { version = "1.52.3", features = ["macros"] }
tokio-test = "0.4.5"
tempfile = "3.27.0"
serial_test = "3.4.0"

[profile.release]
debug = "full"
